= dkr_01

Docker Logging Driver Plugin. Sends the Docker container's logs to the specified RELP server.


== Logging options
These can be modified via the `--log-opt KEY=VALUE` command-line argument when using `docker run`.

* relpHostname = ip address (default: 127.0.0.1)
* relpPort = port number (default: 1601)
* relpTls = "true" or "false" (default: false)
* syslogHostname = used for hostname in the syslog message, otherwise actual system hostname
* syslogAppName = used for app name in the syslog message, otherwise "teragrep"
* tags = "off", "minimal" or "full", sets additional structured data based on docker log tags (default: off)
* k8sMetadata = "true" or "false", fetch kubernetes metadata from specified address (default: false)
* kubeletUrl = "https://xxx:12345", provide kubelet address for kubernetes metadata (default: https://minikube:10250)
* k8sClientAuthEnabled = "true" or "false" (default: true)
* k8sClientAuthCertPath = "..." (default: /var/lib/minikube/certs/apiserver-kubelet-client.crt)
* k8sClientAuthKeyPath = "..." (default: /var/lib/minikube/certs/apiserver-kubelet-client.key)
* k8sServerCertValidationEnabled = "true" or "false" (default: false)
* k8sServerCertPath = "..." (default: none)
* k8sMetadataRefreshInterval = "0" in seconds (default: 0)
* k8sMetadataRefreshEnabled = "true" or "false" (default: false)

== Building the plugin

In git root, run:
[,bash]
----
$ chmod +x build.sh && bash build.sh
----
Will make the plugin and enable it. You can check if it was successful with the `docker plugin ls` command.
The plugin's logs can be accessed from the `/run/docker/plugins/<id>/` folder.

== Running the plugin with a container

To attach the log driver to a container, run the container with the `--log-driver=teragrep/dkr_01:v1` parameter.
[,bash]
----
$ docker run --log-driver=teragrep/dkr_01:v1 \
    --log-opt relpHostname=127.0.0.1 \
    --log-opt relpPort=1234 \
    --log-opt relpTls=false
----

If using the `docker-compose` command, you can customize the `docker-compose.yaml` to contain the
`options`.

[,yaml]
----
x-logging:
    &default-logging
    options:
        relpHostname: "127.0.0.1"
        relpPort: "1601"
    driver: teragrep/dkr_01:v1
services:
    test:
        build:
            context: .
            dockerfile: Dockerfile
        logging: *default-logging
----

== Using in Minikube

To build and use the plugin in Minikube, follow the instructions below.

(Note: In the commands below, `[host]$` means that the command should be run in the
host machine's terminal, `[minikube]$` means that it should be run in minikube ssh, and
`[testserver-pod]$` means that it should be run in the pod's terminal.)

* Start your Minikube environment with

[,bash]
----
[host]$ minikube start
----

* Eval the docker-env to in your host machine's terminal

[,bash]
----
[host]$ eval $(minikube -p minikube docker-env)
----

* Build the plugin

[,bash]
----
[host]$ chmod +x build.sh && bash build.sh
----

* If necessary, build the test server

[,bash]
----
[host]$ cd testserver && docker build . -t testserver:latest --no-cache
----

* SSH to the minikube

[,bash]
----
[host]$ minikube ssh
----

* You need to add the log driver into the dockerd launch command in the `docker.service` file

[,bash]
----
[minikube]$ sudo vi /lib/systemd/system/docker.service
----

Change the line "ExecStart=" to contain the `--log-driver=teragrep/dkr_01:v1` option and any possible
log opts.

* Reload the daemon, restart docker service and restart kubelet to save these changes.

[,bash]
----
[minikube]$ sudo systemctl daemon-reload
[minikube]$ sudo service docker restart
[minikube]$ sudo systemctl restart kubelet
----

* You can check if the logging driver is functioning with the command below in minikube ssh terminal:

[,bash]
----
[minikube]$ docker info | grep -i "logging driver"
----

It should display dkr_01 instead of the default jsonfile logging driver, if the plugin
has been loaded correctly.

If you built the test server, you can run it with (in your host machine terminal):

[,bash]
----
[host]$ kubectl run dkrpod --image=testserver:latest --image-pull-policy=Never --restart=Never
----

To print logs, you can use the pod's terminal and curl

[,bash]
----
[host]$ kubectl exec -i -t dkrpod -- /bin/bash
----

and enter

[,bash]
----
[testserver-pod]$ curl localhost:9003/foobar
----

to generate log output in the testserver pod.