#golang
FROM golang:1.19

#set destination for copy
WORKDIR /relpapp
COPY / ./
RUN go get
RUN CGO_ENABLED=0 GOOS=linux go build -o /usr/bin/relp-docker-plugin
EXPOSE 1601
#CMD ["/usr/bin/relp-docker-plugin"]