version: "3.9"
x-logging:
  &default-logging
  options:
    relpHostname: "127.0.0.1"
    relpPort: "1601"
    tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  driver: teragrep/dkr_01:v1
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    logging: *default-logging
    environment:
      HTTP_PORT: 9003
    extra_hosts: #this is for relp
      - "host.docker.internal:host-gateway"
    network_mode: "host"
